// <auto-generated />
using ContactPage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactPage.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20210525122506_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactPage.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnName("nvarchar(150)");

                    b.Property<string>("CompletedProjects")
                        .HasColumnName("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasColumnName("nvarchar(250)");

                    b.Property<string>("FieldOfActivity")
                        .IsRequired()
                        .HasColumnName("nvarchar(200)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnName("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnName("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("nvarchar(25)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("nvarchar(11)");

                    b.Property<string>("Surname")
                        .HasColumnName("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
